# Site settings
title: Bucket of Tears
description: Cybersecurity is fun, but it is always so challenging that it makes me cry buckets of tears!
url: "https://bucketoftears.netlify.app"

# Google Analytics
google_analytics: UA-123756712-5

# Author
author:
  name: BoT

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 10

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]
